# Generated by Django 3.1.7 on 2021-03-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('I', 'info'), ('P', 'primary'), ('D', 'danger')], default='TS', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('I', 'info'), ('P', 'primary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
