# Generated by Django 3.1.7 on 2021-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210307_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'T-Shirt'), ('HD', 'Hoodie'), ('JK', 'Jacket'), ('ST', 'Sweater')], max_length=2),
        ),
    ]
