# Generated by Django 3.1.7 on 2021-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210307_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Clothes'), ('S', 'Shoes'), ('A', 'Accessories'), ('W', 'Watches')], max_length=1),
        ),
    ]
