# Generated by Django 3.1.7 on 2021-03-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('core', '0014_auto_20210325_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='subregion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion'),
            preserve_default=False,
        ),
    ]
