# Generated by Django 3.1.7 on 2021-04-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210415_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition_number',
            field=models.PositiveIntegerField(default='7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'info'), ('U', 'primary')], max_length=1, null=True),
        ),
    ]
