# Generated by Django 3.1.7 on 2021-05-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210420_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='product-2.jpg', upload_to='product_images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
