# Generated by Django 3.1.7 on 2021-03-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210327_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(default='+84123456789', max_length=12),
            preserve_default=False,
        ),
    ]
