# Generated by Django 3.1.7 on 2021-04-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210404_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='stress_address',
            new_name='street_address',
        ),
    ]
