# Generated by Django 3.1.7 on 2021-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default='10'),
            preserve_default=False,
        ),
    ]
